import Head from 'next/head';
// components
import Card from '../components/UI/UICard';
// data
import { projects } from '../mocks/data';
// styles
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
		<Head>
			<title>Institut du Design</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<main>
			{projects.map((project) => {
				return (
					<Card 
						key={project.id} 
						title={project.title} 
						text={project.text}
						// img={project.img}
						// alt={project.alt}
					/>
				)
			})}
		</main>
    </div>
  )
}
